(lang dune 2.0)

(name yojson_examples)
(version 0.0.1)
(authors "Georgy Komarov")
(license LGPL-3)
(source (github jubnzv/sandbox))
(maintainers "Georgy Komarov <jubnzv@gmail.com>")

(package
  (name yojson_examples)
  (synopsis "yojson examples"))
