'''
https://www.codewars.com/kata/sum-even-fibonacci-numbers

## Sum Even Fibonacci Numbers

* Write a func named SumEvenFibonacci that takes a parameter of type int and returns a value of type int

* Generate all of the Fibonacci numbers starting with 1 and 2 and ending on the highest number before exceeding the parameter's value 


#### Each new number in the Fibonacci sequence is generated by adding the previous two numbers - by starting with 1 and 2(the input could be smaller), the first 10 numbers will be:


```
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
```

* Sum all of the even numbers you generate and return that int

#### Example:

```
sumEvenFibonacci(8) // returns 10 by adding the even values 2 and 8
```
'''
def fib_even(n):
    a, b = 0, 1
    while a < n+1:
        if a % 2 == 0:
            yield a
        a, b = b, a + b
    yield 0

SumEvenFibonacci = lambda n: sum([i for i in fib_even(n)])

if __name__ == '__main__':
    print(SumEvenFibonacci(1))
    print(SumEvenFibonacci(2))
    print(SumEvenFibonacci(8))
    print(SumEvenFibonacci(111111))

