#+TITLE: Лабораторная работа №6

Начальный процесс создает N связанных в кольцо пронумерованных от 1 до
N дочерних, и передает первому из них положительное число M. Данный
процесс разыгрывает по нижеприведенной схеме число P, которое он затем
вычитает из M, и получает Q = M - P.

Если Q меньше или равно нолю, то текущий процесс получает одно
очко. Если его число очков достигает некоторого заданного предела L,
то этот процесс побеждает, и передает свой номер начальному процессу-
создателю кольца.  Создатель завершает игру. Если число очков данного
процесса меньше L, то следующему процессу передается число M.

Если Q больше ноля, то оно передается следующему процессу, который
производит аналогичные действия.

Схема розыгрыша числа P аналогична: в данном случае в качестве
начального процесса выступает разыгрывающий. Он создает еще одно
кольцо из трех процессов, передает первому из них в качестве
начального значение число, полученное от предыдущего процесса, после
чего проводит игру. Для этого кольца значение, вычитаемое каждым
процессом, равно 1. Предел равен L. Число P равно номеру выигравшего
процесса.

Уничтожение колец производится создателем кольца.

Необходимые исполняемые файлы: главный файл, из которого создается
начальный процесс, и файл, из которого начальный процесс создает
составляющие кольца.

Параметры главного исполняемого файла (передаются в командной строке):
1. Количество процессов в главном кольце N;
2. Начальное число M, передаваемое первому процессу;
3. Предел L.

Для взаимодействия процессов использовать следующие механизмы:

| Обмен между создателем и членами главного кольца | Потоковые сокеты     |
| Обмен в главном кольце                           | Разделяемая память   |
| Обмен между кольцами                             | Очереди сообщений    |
| Обмен во втором кольце                           | Дейтаграммные сокеты |

